### ISSUE TITLE
v 1.1.0 Crash because of ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by OfficialLambdax** [LudoCrypt/The-Corners#6]
The crash might be not caused only by The Corners but i dont understand java so i cant look into it myself.
The Mod is installed into a premade modpack named 'Medieval-Minecraft-[FABRIC]-v19'.

And appears once i enter a dimension and minecraft tries to generate the chunks for your dimensions.

At curseforge it says that Satin is already embedded, so i tried it without the lib first and then added it in after the first crash. But the log doesnt change.

```
[12:23:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3242.method_14357(class_3242.java:186) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[12:23:07] [Server thread/ERROR]: This crash report has been saved to: E:\APC\Sonstiges\MultiMC\instances\Medieval-Minecraft-[FABRIC]-v19\minecraft\crash-reports\crash-2021-10-19_12.23.07-server.txt
[12:23:07] [Server thread/INFO]: Stopping server
[12:23:07] [Server thread/INFO]: Saving players
---- Minecraft Crash Report ----
// Don't do that.

Time: 10/19/21, 12:23 PM
Description: Exception generating new chunk

java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:562)

-- Chunk to be generated --
Details:
	Location: 11,1
	Position hash: 4294967307
	Generator: net.ludocrypt.corners.world.chunk.CommunalCorridorsChunkGenerator@6dacb4d
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:562)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by LudoCrypt** [comment]
hmm ill look into this

**Comment by OfficialLambdax** [comment]
Let me know if you need me for something (:

**Comment by bartsimon** [comment]
seems like i am getting the same thing -- overworld painting works but this crash seemed to come with the "backrooms"
[crash-2021-10-24_21.37.46-server.txt](https://github.com/LudoCrypt/The-Corners/files/7406693/crash-2021-10-24_21.37.46-server.txt)

**Comment by OfficialLambdax** [comment]
closed duo to inactivity
